2020-10-19 23:51:03 [[31merror[39m]: uncaughtException: Oops!
Error: Oops!
    at Object.<anonymous> (E:\rs-node\nodejs-course-template\src\app.js:45:7)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (E:\rs-node\nodejs-course-template\src\server.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
2020-10-19 23:51:04 [[31merror[39m]: Captured error: Oops!
2020-10-19 23:51:40 [[31merror[39m]: Unhandled rejection detected: Oops!
2020-10-19 23:53:02 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-20 00:01:33 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-20 00:01:53 [[31merror[39m]: {"status":400,"message":"Bad Request"}
2020-10-20 00:02:09 [[31merror[39m]: uncaughtException: Oops!
Error: Oops!
    at Object.<anonymous> (E:\rs-node\nodejs-course-template\src\app.js:36:7)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (E:\rs-node\nodejs-course-template\src\server.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
2020-10-20 00:02:09 [[31merror[39m]: Captured error: Oops!
2020-10-20 00:02:27 [[31merror[39m]: Unhandled rejection detected: Oops!
2020-10-22 11:33:08 [[31merror[39m]: uncaughtException: Cannot find module 'http-status-codes'
Error: Cannot find module 'http-status-codes'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/common/error.js:1:50)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2020-10-22 11:33:47 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-22 11:33:47 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-22 11:33:47 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-22 11:33:47 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-22 11:33:47 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-22 11:33:47 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-22 11:33:47 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-22 11:57:58 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-22 11:58:58 [[31merror[39m]: Unhandled rejection detected: logger is not defined
2020-10-22 12:00:13 [[31merror[39m]: TypeError: NotFoundError is not a constructor
    at Object.remove (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.memory.repository.js:19:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-22 12:03:33 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:08:35 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-22 12:10:47 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:15:51 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:15:51 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-22 12:15:51 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:15:51 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:15:51 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:15:51 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:15:51 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:16:26 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:16:26 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:16:26 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:16:26 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:16:26 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:16:26 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:16:26 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:23:40 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:23:40 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:23:40 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:23:40 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:23:40 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:23:40 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:23:40 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:31:28 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:31:28 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:31:28 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:31:28 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:31:28 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:31:28 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:31:28 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-22 12:33:58 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 18:50:57 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 18:50:57 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 18:50:57 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 18:50:57 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 18:50:57 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 18:50:57 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 18:50:57 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 18:51:29 [[31merror[39m]: Unhandled rejection detected: 
2020-10-26 18:51:54 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 19:06:27 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 19:06:27 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 19:06:27 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 19:06:27 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 19:06:27 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 19:06:27 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 19:06:27 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 19:30:37 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 19:30:37 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 19:30:38 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 19:30:38 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 19:30:38 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 19:30:38 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-26 19:30:38 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-27 18:50:10 [[31merror[39m]: uncaughtException: logger.info is not a function
TypeError: logger.info is not a function
    at NativeConnection.db.on.once (/home/max/Work/rs/nodejs-course-template/src/server.js:18:12)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at _setClient (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/connection.js:950:8)
    at client.connect (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/connection.js:797:7)
    at /home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/utils.js:674:5
    at err (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/mongo_client.js:225:7)
    at connectCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/core/sdam/topology.js:681:26)
    at fn (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/cmap/connection_pool.js:350:13)
    at handleOperationResult (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (events.js:198:13)
    at processIncomingData (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
2020-10-27 18:50:10 [[31merror[39m]: Captured error: logger.info is not a function
2020-10-27 18:50:41 [[31merror[39m]: uncaughtException: Cannot read property 'info' of undefined
TypeError: Cannot read property 'info' of undefined
    at NativeConnection.db.on.once (/home/max/Work/rs/nodejs-course-template/src/server.js:18:12)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at _setClient (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/connection.js:950:8)
    at client.connect (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/connection.js:797:7)
    at /home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/utils.js:674:5
    at err (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/mongo_client.js:225:7)
    at connectCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/core/sdam/topology.js:681:26)
    at fn (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/cmap/connection_pool.js:350:13)
    at handleOperationResult (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (events.js:198:13)
    at processIncomingData (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
2020-10-27 18:50:41 [[31merror[39m]: Captured error: Cannot read property 'info' of undefined
2020-10-27 18:52:01 [[31merror[39m]: uncaughtException: logger is not defined
ReferenceError: logger is not defined
    at NativeConnection.db.on.once (/home/max/Work/rs/nodejs-course-template/src/server.js:18:5)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at _setClient (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/connection.js:950:8)
    at client.connect (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/connection.js:797:7)
    at /home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/utils.js:674:5
    at err (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/mongo_client.js:225:7)
    at connectCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/core/sdam/topology.js:681:26)
    at fn (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/cmap/connection_pool.js:350:13)
    at handleOperationResult (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (events.js:198:13)
    at processIncomingData (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
2020-10-27 18:52:01 [[31merror[39m]: Captured error: logger is not defined
2020-10-27 18:52:05 [[31merror[39m]: uncaughtException: logger is not defined
ReferenceError: logger is not defined
    at NativeConnection.db.on.once (/home/max/Work/rs/nodejs-course-template/src/server.js:18:5)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at _setClient (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/connection.js:950:8)
    at client.connect (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/connection.js:797:7)
    at /home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/utils.js:674:5
    at err (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/mongo_client.js:225:7)
    at connectCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/core/sdam/topology.js:681:26)
    at fn (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/cmap/connection_pool.js:350:13)
    at handleOperationResult (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/cmap/connection.js:277:5)
    at MessageStream.emit (events.js:198:13)
    at processIncomingData (/home/max/Work/rs/nodejs-course-template/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
2020-10-27 18:52:05 [[31merror[39m]: Captured error: logger is not defined
2020-10-27 19:02:35 [[31merror[39m]: uncaughtException: Unexpected identifier
/home/max/Work/rs/nodejs-course-template/src/resources/users/user.model.js:1
import mongoose from 'mongoose';
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.router.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/app.js:5:20)
2020-10-27 19:13:59 [[31merror[39m]: uncaughtException: Unexpected identifier
/home/max/Work/rs/nodejs-course-template/src/resources/users/user.model.js:1
import mongoose from 'mongoose';
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.router.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/app.js:5:20)
2020-10-27 19:15:17 [[31merror[39m]: uncaughtException: Unexpected identifier
/home/max/Work/rs/nodejs-course-template/src/resources/users/user.model.js:1
import mongoose from 'mongoose';
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.router.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/app.js:5:20)
2020-10-27 19:16:14 [[31merror[39m]: uncaughtException: Unexpected identifier
/home/max/Work/rs/nodejs-course-template/src/resources/users/user.model.js:1
import mongoose from 'mongoose';
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.router.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/app.js:5:20)
2020-10-27 19:16:29 [[31merror[39m]: uncaughtException: Unexpected identifier
/home/max/Work/rs/nodejs-course-template/src/resources/users/user.model.js:1
import mongoose from 'mongoose';
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.router.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/app.js:5:20)
2020-10-27 19:16:32 [[31merror[39m]: uncaughtException: Unexpected identifier
/home/max/Work/rs/nodejs-course-template/src/resources/users/user.model.js:1
import mongoose from 'mongoose';
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.router.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/app.js:5:20)
2020-10-27 19:16:47 [[31merror[39m]: uncaughtException: Unexpected identifier
/home/max/Work/rs/nodejs-course-template/src/resources/users/user.model.js:1
import mongoose from 'mongoose';
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.router.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/app.js:5:20)
2020-10-27 19:16:56 [[31merror[39m]: uncaughtException: Unexpected identifier
/home/max/Work/rs/nodejs-course-template/src/resources/users/user.model.js:1
import mongoose from 'mongoose';
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.router.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/app.js:5:20)
2020-10-27 19:29:29 [[31merror[39m]: uncaughtException: Unexpected identifier
/home/max/Work/rs/nodejs-course-template/src/resources/users/user.model.js:1
import mongoose from 'mongoose';
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.router.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/app.js:5:20)
2020-10-27 19:31:07 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-27 19:36:02 [[31merror[39m]: TypeError: undefined is not a function
    at Array.map (<anonymous>)
    at router.route.get (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.router.js:9:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-27 19:36:02 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-27 19:37:33 [[31merror[39m]: {"status":500,"message":"Internal Server Error stack:TypeError: undefined is not a function\n    at Array.map (<anonymous>)\n    at router.route.get (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.router.js:9:31)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
2020-10-27 19:38:01 [[31merror[39m]: TypeError: undefined is not a function
    at Array.map (<anonymous>)
    at router.route.get (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.router.js:9:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-27 19:38:01 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-27 19:45:14 [[31merror[39m]: TypeError: User.toResponse is not a function
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.router.js:33:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-27 19:45:14 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-27 19:47:35 [[31merror[39m]: uncaughtException: get is not defined
ReferenceError: get is not defined
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.DB.repository.js:9:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.service.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
2020-10-27 19:48:37 [[31merror[39m]: uncaughtException: get is not defined
ReferenceError: get is not defined
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.DB.repository.js:9:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.service.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
2020-10-27 19:55:14 [[31merror[39m]: uncaughtException: User is not a constructor
TypeError: User is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:27:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-27 19:56:08 [[31merror[39m]: uncaughtException: User is not a constructor
TypeError: User is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:27:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-27 19:56:49 [[31merror[39m]: uncaughtException: User is not a constructor
TypeError: User is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:27:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-28 11:44:41 [[31merror[39m]: TypeError: usersRepo.update is not a function
    at Object.update (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.service.js:7:40)
    at router.route.put (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.router.js:40:37)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at /home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/index.js:281:22
    at param (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/index.js:354:14)
    at param (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/index.js:410:3)
    at next (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/index.js:174:3)
    at router (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/index.js:47:12)
    at newFn (/home/max/Work/rs/nodejs-course-template/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/index.js:317:13)
2020-10-28 11:44:41 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 11:46:41 [[31merror[39m]: TypeError: Cannot read property 'updateMany' of undefined
    at Object.remove (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.DB.repository.js:18:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 11:46:41 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 11:48:53 [[31merror[39m]: uncaughtException: Task is not a constructor
TypeError: Task is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:32:7)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-28 11:49:14 [[31merror[39m]: uncaughtException: Task is not a constructor
TypeError: Task is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:32:7)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-28 11:49:47 [[31merror[39m]: uncaughtException: Task is not a constructor
TypeError: Task is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:32:7)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-28 11:57:49 [[31merror[39m]: uncaughtException: Task is not a constructor
TypeError: Task is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:32:7)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-28 11:58:04 [[31merror[39m]: uncaughtException: Task is not a constructor
TypeError: Task is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:32:7)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-28 11:58:44 [[31merror[39m]: uncaughtException: Task is not a constructor
TypeError: Task is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:32:7)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-28 12:07:54 [[31merror[39m]: uncaughtException: Task is not a constructor
TypeError: Task is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:32:7)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-28 12:08:23 [[31merror[39m]: uncaughtException: Task is not a constructor
TypeError: Task is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:32:7)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-28 12:08:42 [[31merror[39m]: uncaughtException: Task is not a constructor
TypeError: Task is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:32:7)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-28 12:09:05 [[31merror[39m]: uncaughtException: Board is not a constructor
TypeError: Board is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:28:19)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-28 12:09:25 [[31merror[39m]: uncaughtException: Board is not a constructor
TypeError: Board is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:28:19)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-28 12:09:27 [[31merror[39m]: uncaughtException: Board is not a constructor
TypeError: Board is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:28:19)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-28 12:10:31 [[31merror[39m]: uncaughtException: Board is not a constructor
TypeError: Board is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:28:19)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-28 12:11:51 [[31merror[39m]: uncaughtException: Board is not a constructor
TypeError: Board is not a constructor
    at test (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:28:19)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/utils/inMemoryDB.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.memory.repository.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-28 12:14:16 [[31merror[39m]: uncaughtException: Cannot find module '../task.model'
Error: Cannot find module '../task.model'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2020-10-28 12:14:41 [[31merror[39m]: uncaughtException: Cannot find module '../task.model'
Error: Cannot find module '../task.model'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2020-10-28 12:14:45 [[31merror[39m]: uncaughtException: Cannot find module '../task.model'
Error: Cannot find module '../task.model'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2020-10-28 12:15:06 [[31merror[39m]: uncaughtException: Cannot find module '../task.model'
Error: Cannot find module '../task.model'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2020-10-28 12:17:42 [[31merror[39m]: uncaughtException: Cannot find module '../../errors/not-found-error'
Error: Cannot find module '../../errors/not-found-error'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.DB.repository.js:3:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.service.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2020-10-28 12:26:45 [[31merror[39m]: uncaughtException: Cannot find module '../../errors/not-found-error'
Error: Cannot find module '../../errors/not-found-error'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.DB.repository.js:3:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.service.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2020-10-28 12:26:52 [[31merror[39m]: uncaughtException: Cannot find module '../../errors/not-found-error'
Error: Cannot find module '../../errors/not-found-error'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.DB.repository.js:3:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.service.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2020-10-28 12:26:53 [[31merror[39m]: uncaughtException: Cannot find module '../../errors/not-found-error'
Error: Cannot find module '../../errors/not-found-error'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.DB.repository.js:3:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.service.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2020-10-28 12:26:56 [[31merror[39m]: uncaughtException: Cannot find module '../../errors/not-found-error'
Error: Cannot find module '../../errors/not-found-error'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.DB.repository.js:3:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.service.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2020-10-28 12:27:31 [[31merror[39m]: uncaughtException: Cannot find module '../../errors/not-found-error'
Error: Cannot find module '../../errors/not-found-error'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.DB.repository.js:3:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.service.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2020-10-28 12:28:03 [[31merror[39m]: uncaughtException: Cannot find module '../task.model'
Error: Cannot find module '../task.model'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2020-10-28 12:28:09 [[31merror[39m]: uncaughtException: Cannot find module '../task.model'
Error: Cannot find module '../task.model'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2020-10-28 12:32:15 [[31merror[39m]: ReferenceError: Board is not defined
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.router.js:33:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:32:15 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:32:15 [[31merror[39m]: ReferenceError: Board is not defined
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.router.js:33:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:32:15 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:32:15 [[31merror[39m]: ObjectParameterError: Parameter "obj" to Document() must be an object, got undefined
    at model.Document (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/document.js:101:11)
    at model.Model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:106:12)
    at new model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:4687:15)
    at toExecute.push.callback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3053:22)
    at toExecute.forEach (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3089:7)
    at Array.forEach (<anonymous>)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3088:15)
    at Promise (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3023:10)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:21:15)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:6:43)
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.router.js:32:37)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/route.js:137:13)
2020-10-28 12:32:15 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:32:15 [[31merror[39m]: ObjectParameterError: Parameter "obj" to Document() must be an object, got undefined
    at model.Document (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/document.js:101:11)
    at model.Model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:106:12)
    at new model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:4687:15)
    at toExecute.push.callback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3053:22)
    at toExecute.forEach (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3089:7)
    at Array.forEach (<anonymous>)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3088:15)
    at Promise (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3023:10)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:21:15)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:6:43)
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.router.js:32:37)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/route.js:137:13)
2020-10-28 12:32:15 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:32:15 [[31merror[39m]: ObjectParameterError: Parameter "obj" to Document() must be an object, got undefined
    at model.Document (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/document.js:101:11)
    at model.Model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:106:12)
    at new model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:4687:15)
    at toExecute.push.callback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3053:22)
    at toExecute.forEach (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3089:7)
    at Array.forEach (<anonymous>)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3088:15)
    at Promise (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3023:10)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:21:15)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:6:43)
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.router.js:32:37)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/route.js:137:13)
2020-10-28 12:32:15 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:32:15 [[31merror[39m]: CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "tasks"
    at model.Query.exec (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4381:21)
    at model.Query.Query.then (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4473:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:32:15 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:32:15 [[31merror[39m]: CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "tasks"
    at model.Query.exec (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4381:21)
    at model.Query.Query.then (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4473:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:32:15 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:32:15 [[31merror[39m]: CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "boards"
    at model.Query.exec (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4381:21)
    at model.Query.Query.then (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4473:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:32:15 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:32:15 [[31merror[39m]: ReferenceError: Board is not defined
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.router.js:33:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:32:15 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:32:15 [[31merror[39m]: ReferenceError: Board is not defined
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.router.js:33:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:32:15 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:32:15 [[31merror[39m]: CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "boards"
    at model.Query.exec (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4381:21)
    at model.Query.Query.then (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4473:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:32:15 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:32:15 [[31merror[39m]: ReferenceError: Board is not defined
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.router.js:33:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:32:15 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:32:15 [[31merror[39m]: ReferenceError: Board is not defined
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.router.js:33:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:32:15 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:32:15 [[31merror[39m]: CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "boards"
    at model.Query.exec (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4381:21)
    at model.Query.Query.then (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4473:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:32:15 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:32:16 [[31merror[39m]: ReferenceError: Board is not defined
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.router.js:33:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:32:16 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:34:54 [[31merror[39m]: Error
    at Object.remove (/home/max/Work/rs/nodejs-course-template/src/resources/users/user.DB.repository.js:16:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:34:54 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-28 12:37:11 [[31merror[39m]: ObjectParameterError: Parameter "obj" to Document() must be an object, got 5f993a9ec5775831b59741c1
    at model.Document (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/document.js:101:11)
    at model.Model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:106:12)
    at new model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:4687:15)
    at toExecute.push.callback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3053:22)
    at toExecute.forEach (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3089:7)
    at Array.forEach (<anonymous>)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3088:15)
    at Promise (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3023:10)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:21:15)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:6:43)
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.router.js:32:37)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/route.js:137:13)
2020-10-28 12:37:11 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:38:36 [[31merror[39m]: ObjectParameterError: Parameter "obj" to Document() must be an object, got 5f993a9ec5775831b59741c1
    at model.Document (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/document.js:101:11)
    at model.Model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:106:12)
    at new model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:4687:15)
    at toExecute.push.callback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3053:22)
    at toExecute.forEach (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3089:7)
    at Array.forEach (<anonymous>)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3088:15)
    at Promise (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3023:10)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:21:15)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:6:43)
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.router.js:32:37)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/route.js:137:13)
2020-10-28 12:38:36 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:39:25 [[31merror[39m]: ObjectParameterError: Parameter "obj" to Document() must be an object, got 5f993a9ec5775831b59741c1
    at model.Document (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/document.js:101:11)
    at model.Model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:106:12)
    at new model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:4687:15)
    at toExecute.push.callback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3053:22)
    at toExecute.forEach (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3089:7)
    at Array.forEach (<anonymous>)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3088:15)
    at Promise (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3023:10)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:21:15)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:6:43)
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.router.js:32:37)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/route.js:137:13)
2020-10-28 12:39:25 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:45:26 [[31merror[39m]: ObjectParameterError: Parameter "obj" to Document() must be an object, got 5f993a9ec5775831b59741c1
    at model.Document (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/document.js:101:11)
    at model.Model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:106:12)
    at new model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:4687:15)
    at toExecute.push.callback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3053:22)
    at toExecute.forEach (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3089:7)
    at Array.forEach (<anonymous>)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3088:15)
    at Promise (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3023:10)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:21:15)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:6:43)
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.router.js:32:37)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/route.js:137:13)
2020-10-28 12:45:26 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:49:06 [[31merror[39m]: ReferenceError: Board is not defined
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.router.js:33:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:49:06 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:49:07 [[31merror[39m]: ReferenceError: Board is not defined
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.router.js:33:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:49:07 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:49:07 [[31merror[39m]: ObjectParameterError: Parameter "obj" to Document() must be an object, got undefined
    at model.Document (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/document.js:101:11)
    at model.Model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:106:12)
    at new model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:4687:15)
    at toExecute.push.callback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3053:22)
    at toExecute.forEach (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3089:7)
    at Array.forEach (<anonymous>)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3088:15)
    at Promise (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3023:10)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:21:15)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:6:43)
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.router.js:32:37)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/route.js:137:13)
2020-10-28 12:49:07 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:49:07 [[31merror[39m]: ReferenceError: Board is not defined
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.router.js:33:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:49:07 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:49:07 [[31merror[39m]: ReferenceError: Board is not defined
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.router.js:33:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:49:07 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:49:07 [[31merror[39m]: CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "boards"
    at model.Query.exec (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4381:21)
    at model.Query.Query.then (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4473:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:49:07 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:49:07 [[31merror[39m]: ObjectParameterError: Parameter "obj" to Document() must be an object, got undefined
    at model.Document (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/document.js:101:11)
    at model.Model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:106:12)
    at new model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:4687:15)
    at toExecute.push.callback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3053:22)
    at toExecute.forEach (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3089:7)
    at Array.forEach (<anonymous>)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3088:15)
    at Promise (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3023:10)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:21:15)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:6:43)
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.router.js:32:37)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/route.js:137:13)
2020-10-28 12:49:07 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:49:07 [[31merror[39m]: ObjectParameterError: Parameter "obj" to Document() must be an object, got undefined
    at model.Document (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/document.js:101:11)
    at model.Model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:106:12)
    at new model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:4687:15)
    at toExecute.push.callback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3053:22)
    at toExecute.forEach (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3089:7)
    at Array.forEach (<anonymous>)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3088:15)
    at Promise (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3023:10)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:21:15)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:6:43)
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.router.js:32:37)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/route.js:137:13)
2020-10-28 12:49:07 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:49:07 [[31merror[39m]: CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "tasks"
    at model.Query.exec (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4381:21)
    at model.Query.Query.then (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4473:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:49:07 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:49:07 [[31merror[39m]: CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "tasks"
    at model.Query.exec (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4381:21)
    at model.Query.Query.then (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4473:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:49:07 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:49:07 [[31merror[39m]: CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "boards"
    at model.Query.exec (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4381:21)
    at model.Query.Query.then (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4473:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:49:07 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:49:07 [[31merror[39m]: ReferenceError: Board is not defined
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.router.js:33:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:49:07 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:49:07 [[31merror[39m]: ReferenceError: Board is not defined
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.router.js:33:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:49:07 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:49:07 [[31merror[39m]: CastError: Cast to ObjectId failed for value "undefined" at path "_id" for model "boards"
    at model.Query.exec (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4381:21)
    at model.Query.Query.then (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/query.js:4473:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:49:07 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:49:08 [[31merror[39m]: ReferenceError: Board is not defined
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.router.js:33:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:49:08 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:51:21 [[31merror[39m]: ObjectParameterError: Parameter "obj" to Document() must be an object, got 5f993a9ec5775831b59741c1
    at model.Document (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/document.js:101:11)
    at model.Model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:106:12)
    at new model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:4687:15)
    at toExecute.push.callback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3053:22)
    at toExecute.forEach (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3089:7)
    at Array.forEach (<anonymous>)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3088:15)
    at Promise (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3023:10)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:21:15)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:6:43)
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.router.js:32:37)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/route.js:137:13)
2020-10-28 12:51:21 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:52:21 [[31merror[39m]: ReferenceError: Board is not defined
    at router.route.put (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.router.js:41:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 12:52:21 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:53:45 [[31merror[39m]: ObjectParameterError: Parameter "obj" to Document() must be an object, got 5f993a9fc5775831b59741c9
    at model.Document (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/document.js:101:11)
    at model.Model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:106:12)
    at new model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:4687:15)
    at toExecute.push.callback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3053:22)
    at toExecute.forEach (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3089:7)
    at Array.forEach (<anonymous>)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3088:15)
    at Promise (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3023:10)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:21:15)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:6:43)
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.router.js:32:37)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/route.js:137:13)
2020-10-28 12:53:45 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 12:53:52 [[31merror[39m]: ObjectParameterError: Parameter "obj" to Document() must be an object, got 5f993a9fc5775831b59741c9
    at model.Document (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/document.js:101:11)
    at model.Model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:106:12)
    at new model (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:4687:15)
    at toExecute.push.callback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3053:22)
    at toExecute.forEach (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3089:7)
    at Array.forEach (<anonymous>)
    at cb (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3088:15)
    at Promise (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/home/max/Work/rs/nodejs-course-template/node_modules/mongoose/lib/model.js:3023:10)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:21:15)
    at Object.save (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.service.js:6:43)
    at router.route.post (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.router.js:32:37)
    at Layer.handle [as handle_request] (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/nodejs-course-template/node_modules/express/lib/router/route.js:137:13)
2020-10-28 12:53:52 [[31merror[39m]: {"status":500,"message":"Internal Server Error"}
2020-10-28 13:07:41 [[31merror[39m]: Error
    at Object.get (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:8:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 13:07:41 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-28 13:07:41 [[31merror[39m]: Error
    at Object.get (/home/max/Work/rs/nodejs-course-template/src/resources/boards/board.DB.repository.js:10:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 13:07:41 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-28 13:07:41 [[31merror[39m]: Error
    at Object.get (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:8:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 13:07:41 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-28 13:07:41 [[31merror[39m]: Error
    at Object.get (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:8:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 13:07:41 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-28 13:07:41 [[31merror[39m]: Error
    at Object.get (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:8:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 13:07:41 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-28 13:07:41 [[31merror[39m]: Error
    at Object.get (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:8:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 13:07:41 [[31merror[39m]: {"status":404,"message":"Not Found"}
2020-10-28 13:07:41 [[31merror[39m]: Error
    at Object.get (/home/max/Work/rs/nodejs-course-template/src/resources/tasks/task.DB.repository.js:8:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-28 13:07:41 [[31merror[39m]: {"status":404,"message":"Not Found"}
